(function () {
  const API_ROOT='https://api.github.com', CACHE_PREFIX='portfolio-github-v2:', CACHE_TTL_MS=15*60*1000, REQUEST_TIMEOUT_MS=9000;
  function apiError(code,message,status){const error=new Error(message);error.code=code;error.status=status||0;return error;}
  function cacheRead(key){try{const raw=sessionStorage.getItem(CACHE_PREFIX+key);if(!raw)return null;const entry=JSON.parse(raw);if(!entry.savedAt||Date.now()-entry.savedAt>CACHE_TTL_MS){sessionStorage.removeItem(CACHE_PREFIX+key);return null;}return entry.value;}catch(_error){return null;}}
  function cacheWrite(key,value){try{sessionStorage.setItem(CACHE_PREFIX+key,JSON.stringify({savedAt:Date.now(),value}));}catch(_error){}}
  async function requestJson(path,options){const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(`${API_ROOT}${path}`,{headers:{Accept:'application/vnd.github+json'},signal:controller.signal,cache:options&&options.fresh?'reload':'default'});if(!response.ok){if(response.status===403||response.status===429)throw apiError('rate_limited','GitHub’s public API limit has been reached. Please try again later.',response.status);if(response.status===404)throw apiError('not_found','The requested public repository was not found.',response.status);throw apiError('http_error',`GitHub returned HTTP ${response.status}.`,response.status);}try{return await response.json();}catch(_error){throw apiError('invalid_response','GitHub returned a response that could not be read.');}}catch(error){if(error.name==='AbortError')throw apiError('timeout','GitHub took too long to respond.');if(error.code)throw error;throw apiError('offline','Public GitHub data is temporarily unavailable.');}finally{window.clearTimeout(timeout);}}
  function normalizeRepository(repo){return{name:repo.name||'',fullName:repo.full_name||'',description:repo.description||'',htmlUrl:repo.html_url||'',language:repo.language||'',topics:Array.isArray(repo.topics)?repo.topics:[],updatedAt:repo.updated_at||'',pushedAt:repo.pushed_at||'',defaultBranch:repo.default_branch||'',stars:Number(repo.stargazers_count||0),forks:Number(repo.forks_count||0),openIssues:Number(repo.open_issues_count||0),archived:Boolean(repo.archived),fork:Boolean(repo.fork)};}
  async function loadRepositories(options){const user=window.PORTFOLIO_CONFIG.githubUser,cacheKey=`repos:${user}`,fresh=Boolean(options&&options.fresh),cached=fresh?null:cacheRead(cacheKey);if(cached)return{data:cached,source:'cache'};const response=await requestJson(`/users/${encodeURIComponent(user)}/repos?per_page=100&sort=updated&type=owner`,{fresh});if(!Array.isArray(response))throw apiError('invalid_response','GitHub returned an unexpected repository list.');const repositories=response.map(normalizeRepository);cacheWrite(cacheKey,repositories);return{data:repositories,source:'network'};}
  function normalizeCommit(commit){return{sha:commit.sha||'',htmlUrl:commit.html_url||'',message:commit.commit&&commit.commit.message?commit.commit.message.split('\n')[0]:'Repository update',author:commit.commit&&commit.commit.author?commit.commit.author.name||'':'',date:commit.commit&&commit.commit.author?commit.commit.author.date||'':''};}
  function normalizePullRequest(pr){return{number:pr.number,title:pr.title||'Pull request',state:pr.merged_at?'merged':pr.state||'closed',htmlUrl:pr.html_url||'',updatedAt:pr.updated_at||'',author:pr.user?pr.user.login||'':''};}
  async function loadRepositoryActivity(repoName,options){const user=window.PORTFOLIO_CONFIG.githubUser,cacheKey=`activity:${user}:${repoName}`,fresh=Boolean(options&&options.fresh),cached=fresh?null:cacheRead(cacheKey);if(cached)return{data:cached,source:'cache'};const basePath=`/repos/${encodeURIComponent(user)}/${encodeURIComponent(repoName)}`;const[repo,commits,pulls]=await Promise.all([requestJson(basePath,{fresh}),requestJson(`${basePath}/commits?per_page=5`,{fresh}),requestJson(`${basePath}/pulls?state=all&sort=updated&direction=desc&per_page=4`,{fresh})]);const activity={repository:normalizeRepository(repo),commits:Array.isArray(commits)?commits.map(normalizeCommit):[],pullRequests:Array.isArray(pulls)?pulls.map(normalizePullRequest):[]};cacheWrite(cacheKey,activity);return{data:activity,source:'network'};}
  window.GitHubPortfolioAPI=Object.freeze({loadRepositories,loadRepositoryActivity});
})();
