(function () {
  window.PORTFOLIO_CONFIG = Object.freeze({
    githubUser: 'tepong32',
    featuredRepos: ['grand', 'TraceSync', 'TracePoint'],
    moreRepos: ['xl_tkinter', 'acctgFiles'],
    projects: Object.freeze({
      TracePoint: Object.freeze({repo:'TracePoint',slug:'tracepoint',featured:true,displayName:'TracePoint',category:'Django GovTech workflow',statusLabel:'Paused · integrating into GRAND',statusClass:'paused',summary:'A focused Django implementation of secure, traceable citizen-assistance workflows now informing GRAND’s assistance domain.',problem:'Public requests need continuity without forcing citizen accounts, while staff still need controlled transitions, document review, and an audit-ready history.',role:'Designed the lifecycle policy, service boundaries, public continuation flow, staff actions, and supporting tests.',caseStudyUrl:'/projects/tracepoint/',technologies:['Python','Django','JavaScript','SQL'],accent:'govtech'}),
      TraceSync: Object.freeze({repo:'TraceSync',slug:'tracesync',featured:true,displayName:'TraceSync',category:'Python desktop utility',statusLabel:'Current release · v0.10.0',statusClass:'released',summary:'A Windows utility for saved folder workflows, confidence-aware comparison, selective synchronization, and durable run history.',problem:'Office users need to understand exactly which files will be copied or replaced before a synchronization changes shared data.',role:'Own the architecture, desktop UX, safety policy, persistence, tests, documentation, and release packaging.',caseStudyUrl:'/projects/tracesync/',technologies:['Python','Tkinter','unittest','PyInstaller'],accent:'desktop'}),
      grand: Object.freeze({repo:'grand',slug:'grand',featured:true,displayName:'GRAND',category:'Multi-module Django platform',statusLabel:'Active development',statusClass:'active',summary:'My largest codebase: an LGU operations platform connecting employee, public-service, and administrative workflows.',problem:'Local-government work is split across public requests, employee records, leave, announcements, departments, and back-office processes that need consistent rules and visibility.',role:'Lead product direction, modular Django architecture, workflow design, full-stack implementation, and iterative testing.',caseStudyUrl:'/projects/grand/',technologies:['Python','Django','JavaScript','SQL'],accent:'platform'}),
      xl_tkinter: Object.freeze({repo:'xl_tkinter',slug:'excel-companion',featured:false,displayName:'Excel Companion',summary:'A desktop experiment for supporting spreadsheet-based operational work with a focused interface.',problem:'Reduce repeated manual interactions when processing familiar Excel-based workflows.',role:'Python, Tkinter, and spreadsheet automation exploration.',caseStudyUrl:'',technologies:['Python','Tkinter','Excel']}),
      acctgFiles: Object.freeze({repo:'acctgFiles',slug:'accounting-automation',featured:false,displayName:'Accounting Automation',summary:'A collection of accounting-aware files and utilities created to reduce repetitive work in a municipal accounting office.',problem:'Improve consistency and reduce repeated preparation in payroll, reporting, and document-handling tasks.',role:'Workflow analysis, spreadsheet automation, and operational tooling.',caseStudyUrl:'',technologies:['Excel','Automation','Accounting']})
    })
  });
})();
