(function(){
  const api=window.GitHubPortfolioAPI,repoName=document.body.dataset.projectRepo,status=document.getElementById('activity-status'),metadata=document.getElementById('activity-metadata'),commits=document.getElementById('activity-commits'),pulls=document.getElementById('activity-pulls'),retry=document.getElementById('activity-retry'),formatter=new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric'});
  document.querySelectorAll('[data-current-year]').forEach(target=>{target.textContent=new Date().getFullYear();});
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function date(value){const parsed=new Date(value);return value&&!Number.isNaN(parsed.getTime())?formatter.format(parsed):'Date unavailable';}
  function empty(target,message){target.innerHTML=`<li>${esc(message)}</li>`;}
  function render(activity){const repo=activity.repository;metadata.innerHTML=`<li><strong>${esc(repo.defaultBranch||'Unavailable')}</strong><small>Default branch</small></li><li><strong>${esc(date(repo.pushedAt))}</strong><small>Latest public push</small></li><li><strong>${esc(repo.language||'Not specified')}</strong><small>Primary language</small></li>`;activity.commits.length?commits.innerHTML=activity.commits.map(commit=>`<li><a href="${esc(commit.htmlUrl)}" target="_blank" rel="noopener noreferrer"><strong>${esc(commit.message)}</strong><small>${esc(commit.sha.slice(0,7))} · ${esc(commit.author)} · ${esc(date(commit.date))}</small></a></li>`).join(''):empty(commits,'No public commits were returned by GitHub.');activity.pullRequests.length?pulls.innerHTML=activity.pullRequests.map(pr=>`<li><a href="${esc(pr.htmlUrl)}" target="_blank" rel="noopener noreferrer"><strong>#${esc(pr.number)} ${esc(pr.title)}</strong><small>${esc(pr.state)} · ${esc(date(pr.updatedAt))}</small></a></li>`).join(''):empty(pulls,'No public pull requests were returned by GitHub.');}
  async function load(fresh){status.textContent=fresh?'Refreshing public GitHub activity…':'Loading public GitHub activity…';retry.hidden=true;try{const result=await api.loadRepositoryActivity(repoName,{fresh});render(result.data);status.textContent=`Public activity loaded from ${result.source==='cache'?'the session cache':'GitHub'}.`;}catch(error){empty(metadata,'Repository metadata unavailable.');empty(commits,'Commit activity could not be loaded.');empty(pulls,'Pull request activity could not be loaded.');status.textContent=error.message||'Public GitHub activity is temporarily unavailable.';retry.hidden=false;}}
  retry.addEventListener('click',()=>load(true));load(false);
})();
