(function(){
  const config=window.PORTFOLIO_CONFIG,api=window.GitHubPortfolioAPI,formatter=new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric'});
  document.querySelectorAll('[data-current-year]').forEach(target=>{target.textContent=new Date().getFullYear();});
  const nav=document.getElementById('mainNav');document.querySelectorAll('#mainNav .nav-link').forEach(link=>link.addEventListener('click',()=>{if(window.innerWidth<992&&nav&&nav.classList.contains('show')&&window.bootstrap)window.bootstrap.Collapse.getOrCreateInstance(nav).hide();}));
  if(document.body.dataset.page!=='home')return;
  const featuredTarget=document.getElementById('featured-projects'),feedTarget=document.getElementById('repo-feed'),statusTarget=document.getElementById('repo-status'),retryButton=document.getElementById('repo-retry');
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function date(value){if(!value)return'No public update date';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'No public update date':formatter.format(parsed);}
  function repoMap(repos){return new Map(repos.map(repo=>[repo.name.toLowerCase(),repo]));}
  function chips(repo,project){const live=repo?[repo.language,...repo.topics].filter(Boolean):[];const values=Array.from(new Set([...live,...(project.technologies||[])])).slice(0,4);return values.map(value=>`<span>${esc(value)}</span>`).join('');}
  function renderFeatured(map){featuredTarget.innerHTML=config.featuredRepos.map((name,index)=>{const project=config.projects[name],repo=map.get(project.repo.toLowerCase())||null,column=project.repo==='grand'?'col-12':'col-lg-6';return`<div class="${column}"><article class="project-card featured-card accent-${esc(project.accent)} h-100"><div class="project-topline"><span class="project-number">0${index+1}</span><span class="project-state state-${esc(project.statusClass)}"><span class="status-dot" aria-hidden="true"></span> ${esc(project.statusLabel)}</span></div><p class="card-label">${esc(project.category)}</p><h3>${esc(project.displayName)}</h3><p class="project-summary">${esc(project.summary)}</p><dl class="project-context"><div><dt>Problem</dt><dd>${esc(project.problem)}</dd></div><div><dt>Contribution</dt><dd>${esc(project.role)}</dd></div></dl><div class="tech-list">${chips(repo,project)}</div><div class="project-meta"><span><i class="bi bi-clock-history" aria-hidden="true"></i> Updated ${esc(date(repo&&repo.pushedAt))}</span>${repo?`<span><i class="bi bi-git"></i> ${esc(repo.defaultBranch)}</span>`:''}</div><div class="project-actions"><a class="btn cta-primary" href="${esc(project.caseStudyUrl)}">Read case study <i class="bi bi-arrow-right"></i></a><a class="inline-link" href="${esc(repo?repo.htmlUrl:`https://github.com/${config.githubUser}/${project.repo}`)}" target="_blank" rel="noopener noreferrer">Repository <i class="bi bi-github"></i></a></div></article></div>`;}).join('');}
  function renderMore(map){const cards=config.moreRepos.map(name=>{const project=config.projects[name],repo=map.get(project.repo.toLowerCase());if(!repo)return'';return`<article class="repo-card"><div class="repo-card-topline"><span><i class="bi bi-github"></i> ${esc(repo.fullName)}</span><span>${repo.archived?'Archived':'Public'}</span></div><h3>${esc(project.displayName)}</h3><p>${esc(project.summary)}</p><div class="tech-list">${chips(repo,project)}</div><div class="repo-card-footer"><span>Updated ${esc(date(repo.pushedAt))}</span><a href="${esc(repo.htmlUrl)}" target="_blank" rel="noopener noreferrer">View repository <i class="bi bi-arrow-up-right"></i></a></div></article>`;}).filter(Boolean);feedTarget.innerHTML=cards.length?cards.join(''):'<p class="empty-state">No configured public repositories were returned by GitHub.</p>';feedTarget.setAttribute('aria-busy','false');return cards.length;}
  function unavailable(){feedTarget.innerHTML='<div class="empty-state"><i class="bi bi-cloud-slash"></i><p>Live repository metadata is unavailable. The curated project case studies remain accessible.</p></div>';feedTarget.setAttribute('aria-busy','false');}
  async function load(fresh){statusTarget.textContent=fresh?'Refreshing public repository data…':'Loading public repository data…';retryButton.hidden=true;feedTarget.setAttribute('aria-busy','true');try{const result=await api.loadRepositories({fresh}),map=repoMap(result.data);renderFeatured(map);const count=renderMore(map);statusTarget.textContent=`${count} curated repositories loaded from ${result.source==='cache'?'the session cache':'GitHub'}.`;}catch(error){unavailable();statusTarget.textContent=error.message||'Public GitHub data is temporarily unavailable.';retryButton.hidden=false;}}
  retryButton.addEventListener('click',()=>load(true));renderFeatured(new Map());load(false);
})();
